# Generated by Django 3.1.1 on 2020-09-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='campus',
        ),
        migrations.AlterField(
            model_name='project',
            name='lecture',
            field=models.CharField(max_length=3),
        ),
    ]
