# Generated by Django 3.1.1 on 2020-09-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20200928_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='pdf',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.TextField(),
        ),
    ]
