# Generated by Django 3.1.1 on 2020-11-16 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_auto_20201116_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='pdf',
        ),
    ]
